FROM jryland/dev-env:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update

# Install extra C/C++ development tools
RUN apt install -y cppcheck clang-tidy

# Install development packages
RUN apt install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libglew-dev

