name: documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: jryland/dev-env:latest
    steps:
      - uses: actions/checkout@v1

      - name: Information
        run: |
          echo "OS details:    $(uname -a)"
          echo "GCC version:   $(gcc -v 2>&1 | grep version)"
          echo "Workspace:     $GITHUB_WORKSPACE"

      - name: Generate documentation
        run: |
          git config --global user.name "John Ryland"
          make pdfs
          make doxygen
          sed -i 's/object type="image\/svg+xml" data/img src/g' .build/docs/html/index.html

      - name: Save documentation
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: .build/docs

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Information
        run: |
          echo "OS details:    $(uname -a)"
          echo "GCC version:   $(gcc -v 2>&1 | grep version)"
          echo "Workspace:     $GITHUB_WORKSPACE"

      - name: Switch Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "JohnRyland@users.noreply.github.com"
          git config --global user.name "JohnRyland"          
          git config pull.rebase false
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git branch gh-pages || true
          git checkout gh-pages
          git pull origin gh-pages || true
          git push -u origin gh-pages || true
          mkdir -p Documentation

      - name: Download job1 artifacts
        uses: actions/download-artifact@v1
        with:
          name: documentation
          path: Documentation

      - name: Git add & commit
        working-directory: Documentation
        run: |
          git add .
          git commit -m "Publish documentation" || true
          git pull origin gh-pages || true
          git push -u origin gh-pages || true

