name: documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install tools
        run: |
          sudo apt update
          sudo apt-get install -y doxygen
      - name: Generate documentation
        run: |
          make doxygen
          sed -i 's/object type="image\/svg+xml" data/img src/g' .build/docs/html/index.html

      - name: Save documentation
        uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: .build/docs/html

  job2:
    name: Publish
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Switch Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout gh-pages
          mkdir -p Documentation
      - name: Download job1 artifacts
        uses: actions/download-artifact@v1
        with:
          name: documentation
          path: Documentation

      - name: Git add & commit
        working-directory: Documentation
        run: |
          git config --global user.email "JohnRyland@users.noreply.github.com"
          git config --global user.name "JohnRyland"          
          git add .
          git commit -m "Publish Maths3D documentation"
          git config pull.rebase false
          git pull
          git push
